server:
  port: 9001
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v1
        cluster-name: BJ

